"all":
  "children":
    "mirrors":
      "hosts":
        "mirror-01":
          "ansible_host": "172.236.176.37"
          "region": "in-bom-2"
        "mirror-02":
          "ansible_host": "172.236.161.36"
          "region": "in-bom-2"
        "mirror-03":
          "ansible_host": "172.236.161.17"
          "region": "in-bom-2"
        "mirror-04":
          "ansible_host": "172.236.161.27"
          "region": "in-bom-2"
    "sources":
      "hosts":
        "source-01":
          "ansible_host": "23.239.13.153"
          "region": "us-east"
        "source-02":
          "ansible_host": "45.33.0.98"
          "region": "us-central"
  "vars":
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no"
    "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
    "ansible_user": "root"
