all:
  vars:
    ansible_user: root # default user for SSH
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    demo_hosts:
      hosts:
        fc-lfir-demo:
          ansible_host: 172.236.161.39

    sources:
      hosts:
        source-01:
          ansible_host: 97.107.129.75
          region: us-east

        source-02:
          ansible_host: 173.255.194.175
          region: us-central

    mirrors:
      hosts:
        mirror-01:
          ansible_host: 172.237.44.64
          region: in-bom-2

        mirror-02:
          ansible_host: 172.236.176.37
          region: in-bom-2

        mirror-03:
          ansible_host: 172.237.44.152
          region: in-bom-2

        mirror-04:
          ansible_host: 172.237.44.170
          region: in-bom-2
