"all":
  "children":
    "mirrors":
      "hosts":
        "mirror-01":
          "ansible_host": "172.236.165.31"
          "region": "in-bom-2"
        "mirror-02":
          "ansible_host": "172.236.171.138"
          "region": "in-bom-2"
        "mirror-03":
          "ansible_host": "172.236.182.204"
          "region": "in-bom-2"
        "mirror-04":
          "ansible_host": "172.236.160.124"
          "region": "in-bom-2"
        "mirror-05":
          "ansible_host": "172.236.179.62"
          "region": "in-bom-2"
        "mirror-06":
          "ansible_host": "172.237.41.199"
          "region": "in-bom-2"
        "mirror-07":
          "ansible_host": "172.237.41.17"
          "region": "in-bom-2"
        "mirror-08":
          "ansible_host": "172.236.182.197"
          "region": "in-bom-2"
        "mirror-09":
          "ansible_host": "172.236.161.27"
          "region": "in-bom-2"
        "mirror-10":
          "ansible_host": "172.236.165.28"
          "region": "in-bom-2"
        "mirror-11":
          "ansible_host": "172.237.32.190"
          "region": "in-bom-2"
        "mirror-12":
          "ansible_host": "172.236.182.248"
          "region": "in-bom-2"
        "mirror-13":
          "ansible_host": "172.237.41.136"
          "region": "in-bom-2"
        "mirror-14":
          "ansible_host": "172.236.182.228"
          "region": "in-bom-2"
        "mirror-15":
          "ansible_host": "172.236.182.195"
          "region": "in-bom-2"
        "mirror-16":
          "ansible_host": "172.236.161.17"
          "region": "in-bom-2"
        "mirror-17":
          "ansible_host": "172.237.32.240"
          "region": "in-bom-2"
        "mirror-18":
          "ansible_host": "172.236.184.165"
          "region": "in-bom-2"
        "mirror-19":
          "ansible_host": "172.236.182.238"
          "region": "in-bom-2"
        "mirror-20":
          "ansible_host": "172.236.180.227"
          "region": "in-bom-2"
        "mirror-21":
          "ansible_host": "172.237.44.170"
          "region": "in-bom-2"
        "mirror-22":
          "ansible_host": "172.236.182.145"
          "region": "in-bom-2"
        "mirror-23":
          "ansible_host": "172.237.44.64"
          "region": "in-bom-2"
        "mirror-24":
          "ansible_host": "172.237.32.181"
          "region": "in-bom-2"
        "mirror-25":
          "ansible_host": "172.237.44.152"
          "region": "in-bom-2"
        "mirror-26":
          "ansible_host": "172.236.182.251"
          "region": "in-bom-2"
        "mirror-27":
          "ansible_host": "172.237.32.50"
          "region": "in-bom-2"
        "mirror-28":
          "ansible_host": "172.237.44.174"
          "region": "in-bom-2"
        "mirror-29":
          "ansible_host": "172.236.182.212"
          "region": "in-bom-2"
        "mirror-30":
          "ansible_host": "172.237.32.220"
          "region": "in-bom-2"
    "sources":
      "hosts":
        "source-01":
          "ansible_host": "172.236.161.36"
          "region": "in-bom-2"
        "source-02":
          "ansible_host": "172.237.38.164"
          "region": "in-bom-2"
        "source-03":
          "ansible_host": "172.236.176.37"
          "region": "in-bom-2"
  "vars":
    "ansible_python_interpreter": "/usr/bin/python3"
    "ansible_ssh_common_args": "-o StrictHostKeyChecking=no"
    "ansible_ssh_private_key_file": "~/.ssh/id_ed25519"
    "ansible_user": "root"
